services:
  - type: web
    name: travel4u
    env: docker
    plan: free
    region: oregon
    branch: main
    healthCheckPath: /

    envVars:

      # --- PERFIL ---
      - key: spring.profiles.active
        value: render

      # --- DATABASE: SUPABASE ---
      - key: spring.datasource.url
        value: jdbc:postgresql://db.tiifltprjgtyfimhnezi.supabase.co:5432/postgres

      - key: spring.datasource.username
        value: postgres

      - key: spring.datasource.password
        sync: false   # ingresa la contrase√±a en el panel de Render

      # --- JAVA OPTIONS ---
      - key: JAVA_OPTS
        value: "-Xmx512m -Xms256m -XX:+UseG1GC"
