services:
  - type: web
    name: travel4u
    env: docker
    plan: free
    region: oregon
    branch: main
    healthCheckPath: /

    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: render

      # --- DATABASE: SUPABASE ---
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://db.tiifltprjgtyfimhnezi.supabase.co:5432/postgres

      - key: SPRING_DATASOURCE_USERNAME
        value: postgres

      - key: SPRING_DATASOURCE_PASSWORD
        sync: false    # SE AGREGA DESDE EL PANEL DE RENDER

      # --- JAVA OPTIONS ---
      - key: JAVA_OPTS
        value: "-Xmx512m -Xms256m -XX:+UseG1GC"
